### ISSUE TITLE
Gameguard error 0000007E

### ISSUE THREAD

**Issue by mdlucy** [nazgulsenpai/sbxigncode#2]
Hi,so I just copied the x3.xem file in xigncode folder but when i try to run the game gameguard error pops up and nothing else(I wanted to bypass xigncode cause everytime i tried to play the game 2 errors occurred gameguard E0190304 and xigncode Ex0191009)

**Comment by RandomAhri** [comment]
Could you help me on doing this? I'm stuck and don't know how to run the game.

**Comment by mdlucy** [comment]
Honestly I dont know how it got fixed I mean errors are still there but the
game starts and I played it the only thing I did was clicking on the start
the game on luncher multiple times so three xingcodes started it sounds
ridiculous I know. (I dont use the bypass I deleted it after 0000007E error and verified game files I still have e0190304 and ex0191009 errors but they dont prevent the game from starting)

**Comment by RandomAhri** [comment]
Do you use wine to play? I keep on getting errors when I try to load the program and I can't get the game to run.

I keep on running into the 0xE0191009 problem which then prevents me from playing the game.

**Comment by mdlucy** [comment]
No,only the game luncher(I dont use Linux either )

**Comment by RandomAhri** [comment]
Do you use a windows computer to play? I'm trying to play on a mac and use wine to play the game.

**Comment by mdlucy** [comment]
Yup windows,sorry bro I truly wish I could help you.
